# Import libraries
#### This is a simple exercise for working with data specifically cleaning, organizing, and labeling it.

In [1]:
import numpy as np
import matplotlib.pyplot as ptl
import pandas as pd

# Import dataset

In [21]:
# Reading the dataset file for processing and model building.
dataset = pd.read_csv('../datasets/Data.csv')
print(dataset)

# Separating the columns for variables x and y
x = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values

# print(x)
# print(y)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


# Data Processing

In [22]:
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

# fix missing data
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[: , 1:3])
x[: , 1:3] = imputer.transform(x[: , 1:3])

# print(x)

# Encoding the 'Country' column using OneHotEncoder.
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

print(x)

# Encoding the 'Purchased' column using LabelEncoder.
le = LabelEncoder()
y = le.fit_transform(y)

# print(y)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


# Data partitioning

In [23]:
from sklearn.model_selection import train_test_split

# Splitting the data into training and testing sets.
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

# print(x_train)
# print(x_test)
# print(y_train)
# print(y_test)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


# Feature Scaling

In [25]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
x_train[: , 3:] = sc.fit_transform(x_train[: , 3:])
x_test[: , 3:] = sc.transform(x_test[: , 3:])